{
 "title": "smart_energy-grid",
 "time": { "from": "2026-01-04T22:00:00.000Z", "to": "2026-01-06T13:00:00.000Z" },
 "panels": [
  {
   "title": "Real-Time Power Consumption (Last 1 Hour)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Real-Time Power Consumption (Last 1 Hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "smart_energy_grid",
     "rawSql": "SELECT \r\n  \"timestamp\" AS time,\r\n  power\r\nFROM energy_readings\r\nWHERE $__timeFilter(\"timestamp\")\r\nORDER BY \"timestamp\";\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "2. Daily consumption pattern (today vs yesterday):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "smart_energy_grid",
     "rawSql": "SELECT\r\n  time_bucket('1 hour', \"timestamp\") AS time,\r\n  CASE \r\n    WHEN \"timestamp\"::date = CURRENT_DATE THEN 'Today'\r\n    WHEN \"timestamp\"::date = (CURRENT_DATE - INTERVAL '1 day')::date THEN 'Yesterday'\r\n  END AS metric,\r\n  AVG(power) AS avg_power\r\nFROM energy_readings\r\nWHERE \"timestamp\" >= (CURRENT_DATE - INTERVAL '1 day')\r\n  AND \"timestamp\" < (CURRENT_DATE + INTERVAL '1 day')\r\nGROUP BY 1, 2\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "3. Weekly energy consumption trend:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "smart_energy_grid",
     "rawSql": "SELECT\r\n  DATE(timestamp) as day,\r\n  SUM(energy) as total_energy,\r\n  AVG(power) as avg_power,\r\n  COUNT(DISTINCT meter_id) as active_meters\r\nFROM energy_readings\r\nWHERE timestamp >= NOW() - INTERVAL '7 days'\r\nGROUP BY day\r\nORDER BY day;"
    }
   ]
  },
  {
   "title": "4. Monthly energy usage by region:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "smart_energy_grid",
     "rawSql": "SELECT\r\n  time_bucket('15 minutes', \"timestamp\") AS time,\r\n  AVG(power) AS avg_power\r\nFROM energy_readings\r\nWHERE $__timeFilter(\"timestamp\")\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "5.a ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "smart_energy_grid",
     "rawSql": "SELECT\r\n  time_bucket('15 minutes', \"timestamp\") AS time,\r\n  AVG(power) AS avg_power\r\nFROM energy_readings\r\nWHERE $__timeFilter(\"timestamp\")\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "5. Storage efficiency from compression:",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "smart_energy_grid",
     "rawSql": "SELECT\r\n  bucket AS time,\r\n  avg_power\r\nFROM energy_readings_15min\r\nWHERE $__timeFilter(bucket)\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "6. Storage efficiency from compression:",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "smart_energy_grid",
     "rawSql": "WITH c AS (\r\n  SELECT\r\n    ch.hypertable_name,\r\n    ch.is_compressed,\r\n    s.total_bytes\r\n  FROM timescaledb_information.chunks ch\r\n  JOIN chunks_detailed_size('public.energy_readings') s\r\n    ON s.chunk_schema = ch.chunk_schema\r\n   AND s.chunk_name  = ch.chunk_name\r\n  WHERE ch.hypertable_name LIKE 'energy_readings%'\r\n)\r\nSELECT\r\n  hypertable_name,\r\n  SUM(CASE WHEN is_compressed = false THEN total_bytes ELSE 0 END) AS raw_bytes,\r\n  SUM(CASE WHEN is_compressed = true  THEN total_bytes ELSE 0 END) AS compressed_bytes,\r\n  ROUND(\r\n    SUM(CASE WHEN is_compressed = false THEN total_bytes ELSE 0 END)::numeric\r\n    / NULLIF(SUM(CASE WHEN is_compressed = true THEN total_bytes ELSE 0 END), 0),\r\n    2\r\n  ) AS compression_ratio\r\nFROM c\r\nGROUP BY hypertable_name\r\nORDER BY hypertable_name\r\n"
    }
   ]
  },
  {
   "title": "Chunk distribution by strategy:",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "smart_energy_grid",
     "rawSql": "SELECT \r\n    hypertable_name,\r\n    COUNT(*) AS chunk_count,\r\n\r\n    SUM(\r\n        pg_total_relation_size(\r\n            format('%I.%I', chunk_schema, chunk_name)::regclass\r\n        )\r\n    ) AS total_bytes,\r\n\r\n    CASE \r\n        WHEN hypertable_name = 'energy_readings' THEN '1 day'\r\n        WHEN hypertable_name = 'energy_readings_3h' THEN '3 hours'\r\n        WHEN hypertable_name = 'energy_readings_week' THEN '1 week'\r\n    END AS chunk_interval\r\nFROM timescaledb_information.chunks\r\nWHERE hypertable_name LIKE 'energy_readings%'\r\nGROUP BY hypertable_name\r\nORDER BY hypertable_name;\r\n"
    }
   ]
  }
 ]
}